/*
Implements an SPI (Serial Peripheral Interface) Master module. This module
drives SPI communication with a slave device by generating clock signals,
controlling the chip select signal, and handling data transmission and 
reception. It supports an 8-bit data transfer protocol.

Inputs:
  - clk: System clock input.
  - reset: Asynchronous reset signal, active high.
  - enable: Signal to enable the SPI communication process.
  - data_to_transmit: 8-bit data to be transmitted to the SPI slave.
  - miso: Master In Slave Out (MISO) input for receiving data from the SPI slave.

Outputs:
  - sclk: SPI clock signal generated by a clock divider.
  - ss: Active low chip select signal to enable the SPI slave device.
  - mosi: Master Out Slave In (MOSI) output for sending data to the SPI slave.
  - data_ready: Indicates that data reception is complete.
  - received_data: 8-bit data received from the SPI slave.

Parameters and Configurations:
  - SHIFT_ON, SAMPLE_ON, DISABLE_ON: Timing parameters defining the behavior
    of the SPI clock and state transitions.

FSM Description:
  The SPI master operates based on a finite state machine (FSM) with the 
  following states:
    - IDLE: Waits for the enable signal to start communication.
    - LOAD: Loads the data to be transmitted into a shift register.
    - SAMPLE: Samples the MISO line to receive a bit from the SPI slave.
    - SAMPLE_WAIT: Waits for sclk to be in the SHIFT_ON phase before shifting.
    - SHIFT: Shifts the data in the shift register and updates the MOSI line.
    - SHIFT_WAIT: Waits for sclk to be in the SAMPLE_ON phase before sampling again.
    - COPY_RECEIVED: Copies the received data from the shift register.
    - DONE: Completes the SPI transaction and waits for further commands.

Internal Signals:
  - current_state, next_state: Registers to manage the current and next FSM states.
  - sclk_started: Indicates that the SPI clock is active.
  - sclk_counter: Counter to track the phase of the SPI clock. Resets every 
    20 cycles of the system clock (used for timing adjustments).
  - shift_register: 8-bit register to hold the data being transmitted or received.
  - bit_counter: Counter to track the number of bits transmitted or received.
  - load_input: Control signal to load the transmission data into the shift register.
  - shift_input: Control signal to shift the shift register contents.
  - sample_output: Control signal to sample the MISO line and store the data bit.
  - copy_output: Indicates the completion of an 8-bit transfer.

Functionality:
  1. Synchronizes the SPI clock (sclk) to the system clock using a clock divider.
  2. Implements an 8-bit serial data transmission and reception protocol.
  3. Handles chip select (ss) and ensures proper communication timing.
  4. Provides a signal (data_ready) to indicate completion of a transaction.
*/
module spi_master (
    clk,
    reset,
    sclk,
    ss,
    mosi,
    miso,
    enable,
    data_ready,
    data_to_transmit,
    received_data
);

/* Timing Parameters */
localparam SHIFT_ON = 5'd8;
localparam SAMPLE_ON = 5'd18;
localparam DISABLE_ON = 5'd11;

/* Inputs and Outputs */
input clk, reset, enable;
output reg data_ready;
input [7:0] data_to_transmit;
output reg [7:0] received_data;

/* SCLK signals */
output wire sclk;
wire sclk_started;
reg [4:0] sclk_counter;

/* Communication related */
input miso;
output reg mosi;
reg [7:0] shift_register;
reg [2:0] bit_counter;
 
/* FSM states and outputs */
parameter IDLE = 3'd0;
parameter LOAD = 3'd1;
parameter SAMPLE = 3'd2;
parameter SAMPLE_WAIT = 3'd3;
parameter SHIFT = 3'd4;
parameter SHIFT_WAIT = 3'd5;
parameter COPY_RECEIVED = 3'd6;
parameter DONE = 3'd7;
reg [2:0] current_state, next_state;
output reg ss;
reg load_input, shift_input, sample_output;
wire copy_output;

assign copy_output = bit_counter == 3'd7 && sample_output;

clock_divider clock_divider_inst(.clk(clk), .reset(reset), .new_clk(sclk), .locked_sync(sclk_started));

always @(posedge clk or posedge reset) begin
    if (reset) begin
        sclk_counter <= 5'd0;
    end else if (sclk_started) begin
        if (sclk_counter == 5'd19)
            sclk_counter <= 5'b0;
        else
            sclk_counter <= sclk_counter + 5'b1;
    end else begin
        sclk_counter <= 5'd0;
    end
end

always @(posedge clk or posedge reset) begin
    if (reset) 
        bit_counter <= 3'b0;
    else if (sample_output)
        bit_counter <= bit_counter + 3'b1;
end

always @(posedge clk or posedge reset) begin
    if (reset)
        shift_register <= 8'b0;
    else if (load_input)
        shift_register[7:1] <= data_to_transmit[6:0];
    else if (shift_input)
        shift_register <= shift_register << 1;
    else if (sample_output)
        shift_register[0] <= miso;
end

always @(posedge clk or posedge reset) begin
    if (reset)
        mosi <= 1'b0;
    else if (load_input)
        mosi <= data_to_transmit[7];
    else if (shift_input)
        mosi <= shift_register[7];
end

always @(posedge clk or posedge reset) begin
    if (reset)
        received_data <= 8'b0;
    else if (copy_output)
        received_data <= shift_register;
end

always @(posedge clk or posedge reset) begin
    if (reset)
        current_state <= IDLE;
    else
        current_state <= next_state;
end

always @(current_state or enable or sclk_counter or bit_counter) begin
    case (current_state)
        IDLE: next_state = (enable && sclk_counter == SHIFT_ON) ? LOAD : IDLE;
        LOAD: next_state = (sclk_counter == SAMPLE_ON) ? SAMPLE : LOAD;
        SAMPLE: next_state = (bit_counter == 3'd7) ? COPY_RECEIVED : SAMPLE_WAIT;
        SAMPLE_WAIT: next_state = (sclk_counter == SHIFT_ON) ? SHIFT : SAMPLE_WAIT;
        SHIFT: next_state = SHIFT_WAIT;
        SHIFT_WAIT: next_state = (sclk_counter == SAMPLE_ON) ? SAMPLE : SHIFT_WAIT;
        COPY_RECEIVED: next_state = DONE;
        DONE: begin
            if (enable && sclk_counter == SHIFT_ON) begin // Continue the next transmission if enable is high
                next_state = LOAD; 
            end else if (sclk_counter == DISABLE_ON) begin // End communication if enable is low and there no time left to start a new transmission
                next_state = IDLE;
            end else begin
                next_state = DONE;
            end
        end
        default: next_state = IDLE;
    endcase
end

always @(current_state) begin
    case (current_state)
        IDLE: begin
            ss = 1;
            load_input = 0;
            shift_input = 0;
            sample_output = 0;
            data_ready = 0;
        end
        LOAD: begin
            ss = 0;
            load_input = 1;
            shift_input = 0;
            sample_output = 0;
            data_ready = 0;
        end
        SAMPLE: begin
            ss = 0;
            load_input = 0;
            shift_input = 0;
            sample_output = 1;
            data_ready = 0;
        end
        SHIFT: begin
            ss = 0;
            load_input = 0;
            shift_input = 1;
            sample_output = 0;
            data_ready = 0;
        end
        COPY_RECEIVED: begin
            ss = 0;
            load_input = 0;
            shift_input = 0;
            sample_output = 0;
            data_ready = 1;
        end
        DONE: begin
            ss = 0;
            load_input = 0;
            shift_input = 0;
            sample_output = 0;
            data_ready = 0;
        end
        default: begin 
            ss = 0;
            load_input = 0;
            shift_input = 0;
            sample_output = 0;
            data_ready = 0;
        end
    endcase
end

    
endmodule